### PR TITLE
fix clone repo from azure

### PR DESCRIPTION
**Pull request by lesomnus**
Default capabilities (I think) fails as:
```
FATA[2024-09-13T16:43:26Z] failed cloning the repository: unexpected client error: unexpected requesting "https://lesomnus@dev.azure.com/org/porject/_git/repo/git-upload-pack" status code: 400 
```
and its cause is well described at https://github.com/go-git/go-git/blob/v5.5.1/_examples/azure_devops/main.go

### CODE REVIEW

**Comment by noam-codefresh** [comment]
@lesomnus - i assume you tested the fix with your azure-devops account, and that fixed the issue. right?

**Comment by lesomnus** [comment]
> @lesomnus - i assume you tested the fix with your azure-devops account, and that fixed the issue. right?

Yep. You're right.

**Review by noam-codefresh — APPROVED** [review]

**Pull request merged**
