### PR TITLE
CR-7821

### PR DESCRIPTION
**Pull request by elad-codefresh**

### CODE REVIEW

**Comment by roi-codefresh** [comment]
why do we need this?

**Comment by elad-codefresh** [comment]
> why do we need this?

we need to expose the CreateIfNotExist property so that it could be changed via cli flag

**Comment by roi-codefresh** [comment]
I already have a wrapper around it in the cli  @elad-codefresh 
image

**Comment by elad-codefresh** [comment]
> 

yes, I'm aware of it and tried to utilize it for this purpose, but for this scenario it's problematic, as:
1. the flag is parsed only after creating the clone options
2. we can't create the gsCloneOpts only afterwards (after the flag is parsed)
3. we can't currently edit that (currently private) property after gsCloneOpts is created

**Comment by roi-codefresh** [comment]
np

**Review by noam-codefresh — APPROVED** [review]

**Pull request merged**
