### PR TITLE
Add HA manifests

### PR DESCRIPTION
**Pull request by todaywasawesome**
Using HA with Argo CD Autopilot would currently require replicating the kustomization in the `manifests/base` folder into another repo and losing the upstream. Adding an `ha` kustomization will allow users to specify a different base for Argo CD manifests and switch to an HA version. 

Ideally this would be supported with a cli flag aswell but this is a good start.

### CODE REVIEW

**Comment by todaywasawesome** [comment]
I'm not sure why this shows so many commits, do I need to rebase or something? It only shows one file change.

**Comment by noam-codefresh** [comment]
no worries about the commits. the diff is clear and simple.
regarding adding a flag - i think bootstrapping with (after it is merged)
```bash
argocd-autopilot repo bootstrap --app https://github.com/argoproj-labs/argocd-autopilot/manifests/ha
```
will use the new has kustomization for argocd. do you think a special flag just for this use-case is needed (in a future pr)?

**Comment by todaywasawesome** [comment]
@noam-codefresh oh yeah, you're right using the app is sufficient.

**Comment by todaywasawesome** [comment]
@noam-codefresh Docs added

**Pull request merged**
