### PR TITLE
Add Chocolatey support in docs

### PR DESCRIPTION
**Pull request by zacharyrgonzales**

### CODE REVIEW

**Comment by zacharyrgonzales** [comment]
Added argocd-autopilot to chocolatey https://community.chocolatey.org/packages/argocd-autopilot and updated docs.

**Comment by roi-codefresh** [comment]
Thank you @zacharyrgonzales!
Also, is required from us to do something when a new version is released?
Or is it an automatic process in those platforms.

**Comment by zacharyrgonzales** [comment]
> Thank you @zacharyrgonzales! Also, is required from us to do something when a new version is released? Or is it an automatic process in those platforms.

Scoop will use the latest release automatically. Chocolatey has to have the the latest release bundled manually. Let me look into chocolatey. This can be a separate issue.

**Comment by roi-codefresh** [comment]
@zacharyrgonzales so we would probably need to add some step in our release pipeline in order to release a new bundle to Chocolatey. And for now we are locked there on the version you bundled manually?

**Pull request merged**
